// export const PROVINCE_OPTION = [
//     { value: 'An Giang', label: 'An Giang'},
//     { value: 'Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu'},
//     { value: 'Bạc Liêu', label: 'Bạc Liêu'},
//     { value: 'Bắc Giang', label: 'Bắc Giang'},
//     { value: 'Bắc Kạn', label: 'Bắc Kạn'},
//     { value: 'Bắc Ninh', label: 'Bắc Ninh'},
//     { value: 'Bến Tre', label: 'Bến Tre'},
//     { value: 'Bình Dương', label: 'Bình Dương'},
//     { value: 'Bình Định', label: 'Bình Định'},
//     { value: 'Bình Phước', label: 'Bình Phước'},
//     { value: 'Bình Thuận', label: 'Bình Thuận'},
//     { value: 'Cà Mau', label: 'Cà Mau'},
//     { value: 'Cao Bằng', label: 'Cao Bằng'},
//     { value: 'Cần Thơ', label: 'Cần Thơ'},
//     { value: 'Đà Nẵng', label: 'Đà Nẵng'},
//     { value: 'Đắk Lắk', label: 'Đắk Lắk'},
//     { value: 'Đắk Nông', label: 'Đắk Nông'},
//     { value: 'Điện Biên', label: 'Điện Biên'},
//     { value: 'Đồng Tháp', label: 'Đồng Tháp'},
//     { value: 'Gia Lai', label: 'Gia Lai'},
//     { value: 'Hà Giang', label: 'Hà Giang'},
//     { value: 'Hà Nam', label: 'Hà Nam'},
//     { value: 'Hải Phòng', label: 'Hải Phòng'},
//     { value: 'Hải Dương', label: 'Hải Dương'},
//     { value: 'Hà Tĩnh', label: 'Hà Tĩnh'},
//     { value: 'Hà Nội', label: 'Hà Nội'},
//     { value: 'Hưng Yên', label: 'Hưng Yên'},
//     { value: 'Hồ Chí Minh', label: 'Hồ Chí Minh'},
//     { value: 'Hòa Bình', label: 'Hòa Bình'},
//     { value: 'Hậu Giang', label: 'Hậu Giang'},
//     { value: 'Lai Châu', label: 'Lai Châu'},
//     { value: 'Kon Tum', label: 'Kon Tum'},
//     { value: 'Kiên Giang', label: 'Kiên Giang'},
//     { value: 'Khánh Hòa', label: 'Khánh Hòa'},
//     { value: 'Long An', label: 'Long An'},
//     { value: 'Lâm Đồng', label: 'Lâm Đồng'},
//     { value: 'Lào Cai', label: 'Lào Cai'},
//     { value: 'Lạng Sơn', label: 'Lạng Sơn'},
//     { value: 'Ninh Thuận', label: 'Ninh Thuận'},
//     { value: 'Ninh Bình', label: 'Ninh Bình'},
//     { value: 'Nghệ An', label: 'Nghệ An'},
//     { value: 'Nam Định', label: 'Nam Định'},
//     { value: 'Quảng Nam', label: 'Quảng Nam'},
//     { value: 'Quảng Bình', label: 'Quảng Bình'},
//     { value: 'Phú Yên', label: 'Phú Yên'},
//     { value: 'Phú Thọ', label: 'Phú Thọ'},
//     { value: 'Sóc Trăng', label: 'Sóc Trăng'},
//     { value: 'Quảng Trị', label: 'Quảng Trị'},
//     { value: 'Quảng Ninh', label: 'Quảng Ninh'},
//     { value: 'Quảng Ngãi', label: 'Quảng Ngãi'},
//     { value: 'Thái Nguyên', label: 'Thái Nguyên'},
//     { value: 'Thái Bình', label: 'Thái Bình'},
//     { value: 'Tây Ninh', label: 'Tây Ninh'},
//     { value: 'Sơn La', label: 'Sơn La'},
//     { value: 'Trà Vinh', label: 'Trà Vinh'},
//     { value: 'Tiền Giang', label: 'Tiền Giang'},
//     { value: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế'},
//     { value: 'Thanh Hóa', label: 'Thanh Hóa'},
//     { value: 'Yên Bái', label: 'Yên Bái'},
//     { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc'},
//     { value: 'Vĩnh Long', label: 'Vĩnh Long'},
//     { value: 'Tuyên Quang', label: 'Tuyên Quang'},
// ];

export const PROVINCE_OPTION = [
    { value: 'an-giang', label: 'An Giang'},
    { value: 'vung-tau', label: 'Bà Rịa - Vũng Tàu'},
    { value: 'bac-lieu', label: 'Bạc Liêu'},
    { value: 'bac-giang', label: 'Bắc Giang'},
    { value: 'bac-kan', label: 'Bắc Kạn'},
    { value: 'bac-ninh', label: 'Bắc Ninh'},
    { value: 'ben-tre', label: 'Bến Tre'},
    { value: 'binh-duong', label: 'Bình Dương'},
    { value: 'binh-dinh', label: 'Bình Định'},
    { value: 'binh-phuoc', label: 'Bình Phước'},
    { value: 'binh-thuan', label: 'Bình Thuận'},
    { value: 'ca-mau', label: 'Cà Mau'},
    { value: 'cao-bang', label: 'Cao Bằng'},
    { value: 'can-tho', label: 'Cần Thơ'},
    { value: 'da-nang', label: 'Đà Nẵng'},
    { value: 'dak-lak', label: 'Đắk Lắk'},
    { value: 'dak-nong', label: 'Đắk Nông'},
    { value: 'dien-bien', label: 'Điện Biên'},
    { value: 'dong-thap', label: 'Đồng Tháp'},
    { value: 'gia-lai', label: 'Gia Lai'},
    { value: 'ha-giang', label: 'Hà Giang'},
    { value: 'ha-nam', label: 'Hà Nam'},
    { value: 'hai-phong', label: 'Hải Phòng'},
    { value: 'hai-duong', label: 'Hải Dương'},
    { value: 'ha-tinh', label: 'Hà Tĩnh'},
    { value: 'ha-noi', label: 'Hà Nội'},
    { value: 'hung-yen', label: 'Hưng Yên'},
    { value: 'ho-chi-minh', label: 'Hồ Chí Minh'},
    { value: 'hoa-binh', label: 'Hòa Bình'},
    { value: 'hau-giang', label: 'Hậu Giang'},
    { value: 'lai-chau', label: 'Lai Châu'},
    { value: 'kon-tum', label: 'Kon Tum'},
    { value: 'kien-giang', label: 'Kiên Giang'},
    { value: 'khanh-hoa', label: 'Khánh Hòa'},
    { value: 'long-an', label: 'Long An'},
    { value: 'lam-dong', label: 'Lâm Đồng'},
    { value: 'lao-cai', label: 'Lào Cai'},
    { value: 'lang-son', label: 'Lạng Sơn'},
    { value: 'ninh-thuan', label: 'Ninh Thuận'},
    { value: 'Ninh-binh', label: 'Ninh Bình'},
    { value: 'nghe-an', label: 'Nghệ An'},
    { value: 'nam-dinh', label: 'Nam Định'},
    { value: 'quang-nam', label: 'Quảng Nam'},
    { value: 'quang-binh', label: 'Quảng Bình'},
    { value: 'phu-yen', label: 'Phú Yên'},
    { value: 'phu-tho', label: 'Phú Thọ'},
    { value: 'soc-trang', label: 'Sóc Trăng'},
    { value: 'quang-tri', label: 'Quảng Trị'},
    { value: 'quang-ninh', label: 'Quảng Ninh'},
    { value: 'quang-ngai', label: 'Quảng Ngãi'},
    { value: 'thai-nguyen', label: 'Thái Nguyên'},
    { value: 'thai-binh', label: 'Thái Bình'},
    { value: 'tay-ninh', label: 'Tây Ninh'},
    { value: 'son-la', label: 'Sơn La'},
    { value: 'tra-vinh', label: 'Trà Vinh'},
    { value: 'tien-giang', label: 'Tiền Giang'},
    { value: 'thua-thien-hue', label: 'Thừa Thiên Huế'},
    { value: 'thanh-hoa', label: 'Thanh Hóa'},
    { value: 'yen-bai', label: 'Yên Bái'},
    { value: 'vinh-phuc', label: 'Vĩnh Phúc'},
    { value: 'vinh-long', label: 'Vĩnh Long'},
    { value: 'tuyen-quang', label: 'Tuyên Quang'},
];

export const CATEGORY_OPTION = [
    { value: 'dia-diem', label: 'Địa Điểm'},
    { value: 'am-thuc', label: 'Ẩm Thực'},
    { value: 'homestay', label: 'Hometay'},
    { value: 'cam-nang', label: 'Cẩm Nang'},
    { value: 'trai-nghiem', label: 'Trải Nghiệm'},
];

export const CATEGORY_CHECK = {
    eat: 'am-thuc',
    entertainment: 'dia-diem',
    homestay: 'homestay',
    handbook: 'cam-nang',
    experience: 'trai-nghiem',
    consious: 'tinh'
}